spring.datasource.url=jdbc:postgresql://db.thajjjdwsfrhxzoujgrc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=5areX6ReW3ZSvSai
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}
spring.servlet.session.cookie.same-site=strict